# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  # desc "Runs all the tests"
  # lane :test do
  #   gradle(task: "test")
  # end

  # desc "Submit a new Beta Build to Crashlytics Beta"
  # lane :beta do
  #   gradle(task: "clean assembleRelease")
  #   crashlytics
  
  #   # sh "your_script.sh"
  #   # You can also use other beta testing services here
  # end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end

  desc "My awesome app"
    lane :distribute do
      appId = "1:5472173958:android:ed37b4956da897973df607"
      latest_release = firebase_app_distribution_get_latest_release(
        app: appId,
      )

      increment_version_code(
        version_code: latest_release[:buildVersion].to_i + 1,
        gradle_file_path: "./app/build.gradle",
      )
      
      gradle(task: 'assemble', build_type: 'Release')

      release = firebase_app_distribution(
          app: appId,
          apk_path: "../build/app/outputs/apk/release/app-release.apk",
          release_notes: "Lots of amazing new features to test out!"
      )
    end
end
