name: test-my-app

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macOS-14

    steps:
      - uses: actions/checkout@v4

      - uses: futureware-tech/simulator-action@v3
        with:
          model: "iPhone 15 Pro Max"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter pub get
      - run: bash ./test-record.sh
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
            name: dist-without-markdown
            path: preview.mp4
